package pruebaJuzgado;
// Generated by Selenium IDE
import java.lang.reflect.Proxy;
import java.time.Duration;
import java.util.*;
import java.util.Arrays;
import java.util.Map;
import java.util.Set;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;



public class pruebaJuzgado {
	  private WebDriver driver;
	  private Map<String, Object> vars;
	  JavascriptExecutor js;
	  String URL = "http://google.com";


 // @Before
  public pruebaJuzgado(WebDriver driver, long timeoutInSeconds) {
	    this(driver, Duration.ofSeconds(timeoutInSeconds));
	  }  
  
  		public pruebaJuzgado(WebDriver driver2, Duration ofSeconds) {
	// TODO Auto-generated constructor stub
}
  		public static void main(String[] args) throws InterruptedException {
  			// TODO Auto-generated method stub
		//public void init() throws InterruptedException {
	
	  		System.setProperty("webdriver.gecko.driver", "D:\\Descargas\\Selenium\\geckodriver.exe");
	
	  		WebDriver driver = new FirefoxDriver();
	  		
	
	  		driver.get("https://authhomo.afip.gob.ar/contribuyente_/login.xhtml");
	  		driver.manage().window().setSize(new Dimension(1366, 728));
	  		driver.findElement(By.id("F1:username")).sendKeys("20310607992");
	  		driver.findElement(By.id("F1:btnSiguiente")).click();
	  		Thread.sleep(2000);
	  		driver.findElement(By.id("F1:password")).sendKeys("Mariano321");
	  		driver.findElement(By.id("F1:btnIngresar")).click();
	  		Thread.sleep(5000);
	  		driver.findElement(By.cssSelector(".h6:nth-child(3) .web-only")).click();
	  		Thread.sleep(2000);
	  		//vars.put("window_handles", driver.getWindowHandles());
	  		WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(60));
	  		driver.findElement(By.cssSelector(".col-lg-4:nth-child(17) .bold")).click();
	  		Thread.sleep(6000);
	  		//vars.put("win9275", waitForWindow(2000));
	  		//driver.switchTo().window(vars.get("win9275").toString());
	  		driver.findElement(By.cssSelector(".text-primary:nth-child(2)")).click();
	  		WebDriverWait wait2 = new WebDriverWait(driver, Duration.ofSeconds(60));
	  		Thread.sleep(2000);
	  		driver.findElement(By.cssSelector(".fa-search")).click();
	  		Thread.sleep(2000);
	  		driver.findElement(By.cssSelector(".odd:nth-child(1) .fa-eye")).click();
	  		Thread.sleep(2000);
  		}
	
/*	driver.get("https://authhomo.afip.gob.ar/contribuyente_/login.xhtml");
    driver.manage().window().setSize(new Dimension(682, 695));
    driver.findElement(By.id("F1:username")).sendKeys("20310607992");
    driver.findElement(By.id("F1:btnSiguiente")).click();
    Thread.sleep(2000);
    driver.findElement(By.id("F1:password")).sendKeys("Mariano321");
    driver.findElement(By.id("F1:btnIngresar")).click();
    Thread.sleep(6000);
    driver.findElement(By.cssSelector(".h6:nth-child(3) .web-only")).click();
    Thread.sleep(6000);
    driver.findElement(By.cssSelector(".rbt-input-main")).click();
    Thread.sleep(8000);
  //  vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".col-lg-4:nth-child(17) .small")).click();
  //  vars.put("win3612", waitForWindow(2000));
    Thread.sleep(2000);
    //driver.switchTo().window(vars.get("win3612").toString());
    Thread.sleep(2000);
    driver.findElement(By.cssSelector(".media-middle")).click();
    driver.findElement(By.cssSelector("#divConsultas .panel-heading")).click();
    Thread.sleep(6000);
    driver.findElement(By.cssSelector(".odd:nth-child(1) .fa-file-pdf-o")).click();
  }*/
 @After
  
  		
  
  		public void testURL() {
  	
  			driver.navigate().to(URL);
  			String title=driver.getTitle();
  			Assert.assertEquals(title, "Google");
  			System.out.println("title:"+title);
  			}

  
  
  			public void tearDown() {
  				//driver.quit();	
  			}
  			
  			public String waitForWindow(int timeout) {
  				try {
  					Thread.sleep(timeout);
  						} catch (InterruptedException e) {
  								e.printStackTrace();
  							}
  				Set<String> whNow = driver.getWindowHandles();
  				Set<String> whThen = (Set<String>) vars.get("window_handles");
  				if (whNow.size() > whThen.size()) {
  				whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  			
}
  //@Test
  
  

