package inquilinoTest;
import java.util.Map;
import java.util.Set;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;


//CLASE INQUILINO
public class INQUILINOTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  String URL = "http://google.com";
  @Before
  
  public void init() 
  {
	  System.setProperty("webdriver.chrome.driver","D:\\Descargas\\chromedriver_win32\\chromedriver.exe");
    driver = new ChromeDriver();
    
//driver = new ChromeDriver(); 
//driver.manage().deleteAllCookies(); 
//driver.manage().window().maximize();
//Runtime.getRuntime().exec("AutoIT_Exe//AutoIT_Login.exe"); 
//driver.get(URL);
    
   // js = (JavascriptExecutor) driver;
   // vars = new HashMap<String, Object>();
    
  
  }
    
    public void testURL() {
    	
    	driver.navigate().to(URL);
    	String title=driver.getTitle();
    	Assert.assertEquals(title, "Google");
    	System.out.println("title:"+title);
    	
    	
    	
    }
  
  @After
  public void tearDown() {
    //driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void iNQUILINO() throws Exception {
    driver.get("https://authhomo.afip.gov.ar/contribuyente_/login.xhtml");
    Thread.sleep(10000);
    driver.findElement(By.id("F1:username")).sendKeys("20310607992");
    driver.findElement(By.id("F1:btnSiguiente")).click();
    Thread.sleep(2000);
    driver.findElement(By.id("F1:password")).sendKeys("Mariano321");
    driver.findElement(By.id("F1:btnIngresar")).click();
    Thread.sleep(10000);
    driver.findElement(By.linkText("Mis Servicios")).click();
    Thread.sleep(8000);
    //vars.put("window_handles", driver.getWindowHandles());
    
    driver.findElement(By.cssSelector(".col-lg-4:nth-child(16) .bold")).click();
    Thread.sleep(8000);
   // vars.put("win5108", waitForWindow(5000));
   // vars.put("root", driver.getWindowHandle());
    driver.findElement(By.cssSelector(".h6:nth-child(3) .web-only")).click();
    Thread.sleep(5000);
    //driver.switchTo().window(vars.get("win5108").toString());
    driver.findElement(By.cssSelector("#\\32 7363591715 .text-uppercase")).click();
    Thread.sleep(5000);
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector("#divContratos .panel-heading")).click();
    driver.findElement(By.id("rbUrbano")).click();
    driver.findElement(By.id("modalMensajeBtnOK")).click();
    driver.findElement(By.id("rbUrbano")).click();
    driver.findElement(By.id("rbSubLocacionSi")).click();
    driver.findElement(By.id("btnSiguiente")).click();
    driver.findElement(By.id("rbLocador")).click();
    driver.findElement(By.id("rbEnNombrePropio")).click();
    driver.findElement(By.id("btnSiguiente")).click();
    driver.findElement(By.cssSelector("#btnNuevoAgregarLocador > .fa")).click();
    driver.findElement(By.id("rbResidenteNo")).click();
    driver.findElement(By.id("txtCuitResidente")).click();
    driver.findElement(By.id("txtPorcLocacion")).sendKeys("100");
    driver.findElement(By.cssSelector("#footer-wait .col-md-12")).click();
    driver.findElement(By.id("btnAgregarLocador")).click();
    driver.findElement(By.id("btnSiguiente")).click();
    driver.findElement(By.cssSelector(".fa-plus")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("btnSiguiente")).click();
    driver.findElement(By.id("rbResidenteNo")).click();
    driver.findElement(By.id("txtCuitResidente")).click();
    driver.findElement(By.id("txtCuitResidente")).click();
    driver.findElement(By.id("txtCuitResidente")).sendKeys("27111141776");
    driver.findElement(By.id("btnAgregarInquilino")).click();
    driver.findElement(By.id("btnAgregarInquilino")).click();
    driver.findElement(By.id("btnSiguiente")).click();
    driver.findElement(By.id("btnSiguiente")).click();
    driver.findElement(By.id("txtCalle")).click();
    driver.findElement(By.id("txtCalle")).sendKeys("peron");
    driver.findElement(By.id("txtNumero")).sendKeys("777");
    driver.findElement(By.id("txtPiso")).sendKeys("6");
    driver.findElement(By.id("txtDepto")).sendKeys("C");
    driver.findElement(By.id("cboProvincia")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cboProvincia"));
      dropdown.findElement(By.xpath("//option[. = 'BUENOS AIRES']")).click();
    }
    driver.findElement(By.id("cboPartido")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cboPartido"));
      dropdown.findElement(By.xpath("//option[. = 'Lanus']")).click();
    }
    driver.findElement(By.id("cboLocalidad")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cboLocalidad"));
      dropdown.findElement(By.xpath("//option[. = 'LANUS ESTE (1824)']")).click();
    }
    driver.findElement(By.id("btnSiguiente")).click();
    driver.findElement(By.id("rbMultipleDomicilioNo")).click();
    driver.findElement(By.id("cboTipoInmueble")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cboTipoInmueble"));
      dropdown.findElement(By.xpath("//option[. = 'Casa']")).click();
    }
    driver.findElement(By.id("cboDestino")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cboDestino"));
      dropdown.findElement(By.xpath("//option[. = 'Otros fines']")).click();
    }
    driver.findElement(By.id("btnSiguiente")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#dvFechaInicio .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("dtpFechaFin")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) > .day:nth-child(5)")).click();
    driver.findElement(By.id("dtpFechaCelebracion")).click();
    driver.findElement(By.id("dtpFechaInicio")).click();
    driver.findElement(By.cssSelector(".fa-plus")).click();
    driver.findElement(By.id("rbModalidadDinero")).click();
    driver.findElement(By.id("cboFrecuenciaPago")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cboFrecuenciaPago"));
      dropdown.findElement(By.xpath("//option[. = 'CUATRIMESTRAL']")).click();
    }
    driver.findElement(By.id("cboMedio")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cboMedio"));
      dropdown.findElement(By.xpath("//option[. = 'EFECTIVO']")).click();
    }
    driver.findElement(By.id("cboTipoMoneda")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cboTipoMoneda"));
      dropdown.findElement(By.xpath("//option[. = 'Pesos Argentinos']")).click();
    }
    driver.findElement(By.id("txtValorMonedaElegida")).click();
    driver.findElement(By.id("txtValorMonedaElegida")).sendKeys("5000");
    driver.findElement(By.id("btnAgregarModalidad")).click();
    {
      WebElement element = driver.findElement(By.id("btnAdjuntar"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".col-md-4:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.id("btnAdjuntar"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("btnAdjuntar")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("btnAdjuntar")).click();
    driver.findElement(By.id("btnAdjuntar")).click();
    driver.findElement(By.id("btnAdjuntar")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.linkText("RELI_Creacion_contrato__Id_70320220610102033.pdf"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("files")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.id("btnAdjuntar"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("btnSiguiente")).click();
    {
      WebElement element = driver.findElement(By.id("btnSiguiente"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("btnSiguiente")).click();
    driver.findElement(By.cssSelector(".text-white:nth-child(2)")).click();
    driver.switchTo().window(vars.get("root").toString());
  }
}
